<?php

namespace App\Notifications;

use App\Models\ActivityProposal;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class ActivityProposalStatusNotification extends Notification
{
    use Queueable;

    public function __construct(
        public ActivityProposal $proposal,
        public string $subjectLine,
        public string $messageLine,
    ) {}

    public function via(object $notifiable): array
    {
        return ['database', 'mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
            ->subject($this->subjectLine)
            ->greeting('Hello ' . ($notifiable->name ?? 'User') . ',')
            ->line($this->messageLine)
            ->line('Reference No.: ' . $this->proposal->proposal_no)
            ->line('Activity: ' . $this->proposal->title)
            ->line('Status: ' . $this->proposal->statusLabel())
            ->action('View Activity Proposal', route('activity-proposals.show', $this->proposal))
            ->line('This message was generated by the NU Clark Integrated Asset, Inventory and Facilities Management System.');
    }

    public function toArray(object $notifiable): array
    {
        return [
            'activity_proposal_id' => $this->proposal->id,
            'proposal_no' => $this->proposal->proposal_no,
            'status' => $this->proposal->status,
            'status_label' => $this->proposal->statusLabel(),
            'subject' => $this->subjectLine,
            'message' => $this->messageLine,
            'url' => route('activity-proposals.show', $this->proposal),
        ];
    }
}
