<?php

namespace App\Notifications;

use App\Models\FacilityReservation;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class FacilityReservationStatusNotification extends Notification
{
    use Queueable;

    public function __construct(
        public FacilityReservation $reservation,
        public string $subjectLine,
        public string $messageLine,
    ) {}

    public function via(object $notifiable): array
    {
        return ['database', 'mail'];
    }

    /**
     * FMO recipients go straight to the reservation's full detail page;
     * requestors go to /facilities, which simply forwards them to their own
     * home page. Nobody is ever sent to a URL their role cannot open.
     */
    private function linkFor(object $notifiable): string
    {
        if (method_exists($notifiable, 'canManageFacilities') && $notifiable->canManageFacilities()) {
            return route('fmo.reservations.show', $this->reservation->id);
        }

        return route('facilities.index');
    }

    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
            ->subject($this->subjectLine)
            ->greeting('Hello ' . ($notifiable->name ?? 'User') . ',')
            ->line($this->messageLine)
            ->line('Reference No.: ' . $this->reservation->reservation_no)
            ->line('Facility: ' . ($this->reservation->facility->name ?? 'N/A'))
            ->line('Status: ' . ucfirst((string) $this->reservation->status))
            ->action('View Reservations', $this->linkFor($notifiable))
            ->line('This message was generated by the NU Clark Asset and Inventory System.');
    }

    public function toArray(object $notifiable): array
    {
        return [
            'reservation_id' => $this->reservation->id,
            'requisition_no' => $this->reservation->reservation_no,
            'status' => $this->reservation->status,
            'status_label' => ucfirst((string) $this->reservation->status),
            'subject' => $this->subjectLine,
            'message' => $this->messageLine,
            'url' => $this->linkFor($notifiable),
        ];
    }
}
