<?php

namespace App\Notifications;

use App\Models\Requisition;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

/**
 * Sent to Asset Management (admin / super_admin) as soon as a requisition is
 * fully approved and is now sitting in the Issuance & Returns queue waiting
 * to be recorded -- so they don't have to keep checking the tab manually.
 */
class IssuanceNeededNotification extends Notification
{
    use Queueable;

    public function __construct(
        public Requisition $requisition,
    ) {}

    public function via(object $notifiable): array
    {
        return ['database', 'mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
            ->subject('New issuance ready to record')
            ->greeting('Hello ' . ($notifiable->name ?? 'User') . ',')
            ->line('Requisition "' . $this->requisition->requisition_no . '" has been fully approved and is now ready to be issued.')
            ->line('Requested by: ' . ($this->requisition->user->name ?? 'N/A'))
            ->line('Department: ' . ($this->requisition->department->name ?? 'N/A'))
            ->action('Record Issuance', route('issuances.create'))
            ->line('This message was generated by the NU Clark Asset and Inventory System.');
    }

    public function toArray(object $notifiable): array
    {
        return [
            'requisition_id' => $this->requisition->id,
            'requisition_no' => $this->requisition->requisition_no,
            'status' => $this->requisition->status,
            'status_label' => $this->requisition->statusLabel(),
            'subject' => 'New issuance ready to record',
            'message' => 'Requisition "' . $this->requisition->requisition_no . '" has been fully approved and needs to be recorded in Issuance & Returns.',
            'url' => route('issuances.create'),
        ];
    }
}
