<?php

namespace App\Notifications;

use App\Models\Issuance;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class IssuanceStatusNotification extends Notification
{
    use Queueable;

    public function __construct(
        public Issuance $issuance,
        public string $subjectLine,
        public string $messageLine,
    ) {}

    public function via(object $notifiable): array
    {
        return ['database', 'mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $requisition = $this->issuance->requisition;

        return (new MailMessage)
            ->subject($this->subjectLine)
            ->greeting('Hello ' . ($notifiable->name ?? 'User') . ',')
            ->line($this->messageLine)
            ->line('Reference No.: ' . ($requisition->requisition_no ?? 'N/A'))
            ->line('Issuance Status: ' . ucfirst((string) $this->issuance->status))
            ->action('View Issuances', route('issuances.index'))
            ->line('This message was generated by the NU Clark Asset and Inventory System.');
    }

    public function toArray(object $notifiable): array
    {
        $requisition = $this->issuance->requisition;

        return [
            'issuance_id' => $this->issuance->id,
            'requisition_no' => $requisition->requisition_no ?? 'N/A',
            'status' => $this->issuance->status,
            'status_label' => ucfirst((string) $this->issuance->status),
            'subject' => $this->subjectLine,
            'message' => $this->messageLine,
            'url' => route('issuances.index'),
        ];
    }
}
