<?php

namespace App\Notifications;

use App\Models\Requisition;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class RequisitionStatusNotification extends Notification
{
    use Queueable;

    public function __construct(
        public Requisition $requisition,
        public string $subjectLine,
        public string $messageLine,
    ) {}

    public function via(object $notifiable): array
    {
        return ['database', 'mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
            ->subject($this->subjectLine)
            ->greeting('Hello ' . ($notifiable->name ?? 'User') . ',')
            ->line($this->messageLine)
            ->line('Reference No.: ' . $this->requisition->requisition_no)
            ->line('Status: ' . $this->requisition->statusLabel())
            ->action('View Requisition', route('requisitions.show', $this->requisition))
            ->line('This message was generated by the NU Clark Asset and Inventory System.');
    }

    public function toArray(object $notifiable): array
    {
        return [
            'requisition_id' => $this->requisition->id,
            'requisition_no' => $this->requisition->requisition_no,
            'status' => $this->requisition->status,
            'status_label' => $this->requisition->statusLabel(),
            'subject' => $this->subjectLine,
            'message' => $this->messageLine,
            'url' => route('requisitions.show', $this->requisition),
        ];
    }
}
