<?php

namespace App\Notifications;

use App\Models\FacilityReservation;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

/**
 | Every step of the emergency-cancellation conversation, in one notification.
 |
 | The requestor has to hear about this twice over: once in the system and once
 | in the inbox they registered with, because an activity that loses its venue
 | at short notice cannot wait for the next login. The Facilities Office also
 | gets the in-system half when a requestor answers.
 */
class ReservationEmergencyNotification extends Notification
{
    use Queueable;

    public function __construct(
        public FacilityReservation $reservation,
        public string $subjectLine,
        public string $messageLine,
        /** Where the recipient should go to act on this. */
        public string $actionUrl,
        public string $actionLabel = 'Open the booking',
        /** Extra lines (reason, offered options, new schedule). */
        public array $details = [],
        /** Mail is skipped for the office's own in-system alerts. */
        public bool $sendMail = true,
    ) {}

    public function via(object $notifiable): array
    {
        return $this->sendMail ? ['database', 'mail'] : ['database'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $mail = (new MailMessage)
            ->subject($this->subjectLine)
            ->greeting('Hello '.($notifiable->name ?? 'User').',')
            ->line($this->messageLine)
            ->line('Reference No.: '.$this->reservation->reservation_no)
            ->line('Activity: '.$this->reservation->title);

        foreach ($this->details as $line) {
            $mail->line($line);
        }

        return $mail
            ->action($this->actionLabel, $this->actionUrl)
            ->line('Your approvals are unchanged — only the schedule is affected.')
            ->line('This message was generated by the NU Clark Integrated Asset, Inventory and Facilities Management System.');
    }

    public function toArray(object $notifiable): array
    {
        return [
            'facility_reservation_id' => $this->reservation->id,
            'requisition_no' => $this->reservation->reservation_no,
            'status' => $this->reservation->rebooking_status,
            'status_label' => $this->reservation->displayStatus(),
            'subject' => $this->subjectLine,
            'message' => $this->messageLine,
            'details' => $this->details,
            'url' => $this->actionUrl,
        ];
    }
}
